default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build Android App Bundle (.aab)"
  lane :build_bundle do
    gradle(
      task: "bundle",
      build_type: "Release"
    )
  end

  desc "Deploy a new version to the Google Play (Internal, Alpha, Beta, or Production)"
  lane :deploy_playstore do |options|
    track = options[:track] || "internal"
    
    upload_to_play_store(
      track: track,
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "draft" # change to 'completed' for immediate publication
    )
  end
end
